#!/bin/bash

# test: Test debops.libvirtd_qemu
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


# Add Ubuntu Trusty repository
echo "deb http://us.archive.ubuntu.com/ubuntu/ trusty main restricted universe multiverse" | sudo tee /etc/apt/sources.list.d/trusty.list
sudo apt-get -qq update
sudo apt-get -y install ubuntu-keyring
sudo apt-get -qq update


ansible-galaxy -f install debops.ferm

assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/libvirt/qemu.conf"
assert_running "libvirtd"
assert_docs
