---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: debops.apache/env

    - role: ansible-checkmk_server/env

    - role: debops.etc_services
      etc_services__dependent_list: '{{ checkmk_server__etc_services__dependent_list }}'

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ apache__ferm__dependent_rules }}'
        - '{{ checkmk_server__ferm__dependent_rules }}'

    - role: debops.apache
      apache__dependent_snippets: '{{ checkmk_server__apache__dependent_snippets }}'
      apache__dependent_vhosts: '{{ checkmk_server__apache__dependent_vhosts }}'

    - role: debops.users
      users__dependent_accounts: '{{ checkmk_server__users__dependent_accounts }}'

    - role: ansible-checkmk_server
