#!/bin/bash

# test: Test debops.monit
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences debops.etc_services


assert_playbook_check_runs
assert_playbook_idempotent


sleep 20

echo "monit --version"
sudo monit --version

echo "monit report"
sudo monit report

echo "monit summary"
sudo monit summary

assert_monitoring "ssh"

assert_running "monit"

assert_docs
