#!/bin/bash

# test: Test debops.unbound
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

sudo apt-get install -yq dnsutils

ansible-galaxy -f install debops.apt_preferences debops.etc_services


assert_playbook_check_runs
assert_playbook_idempotent


echo "Check if unbound is working"
sudo unbound-control status

echo "Test: dig @127.0.0.1 travis-ci.org"
dig @127.0.0.1 travis-ci.org


assert_docs
