#!/bin/bash

# test: Test debops.dovecot
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.pki debops.postfix debops.ferm debops.secret


upgrade_packages dovecot-core dovecot-imapd


echo "Contents of /etc/postfix/main.cf"
cat /etc/postfix/main.cf

echo "Contents of /etc/postfix/master.cf"
cat /etc/postfix/master.cf

assert_playbook_check_runs
assert_playbook_idempotent

assert_path "/etc/dovecot/local.conf"
assert_running "dovecot"

assert_tcp "localhost" "143"
assert_iptables_allow imap

assert_tcp "localhost" "993"
assert_iptables_allow imaps

# Test documentation
assert_docs

