#!/bin/bash

# test: Test debops.mysql
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.ferm debops.tcpwrappers

sudo apt-get -yq install tree

stop mysql
purge ${ROLESPEC_MYSQL_LIBS}
sudo rm -rf /etc/mysql /var/lib/mysql


assert_playbook_check_runs
assert_playbook_idempotent


echo "Contents of /etc/mysql"
tree /etc/mysql

echo "Contents of /root/.my.cnf"
sudo cat /root/.my.cnf

echo "Test if mysql root commands work"
sudo mysql -e 'show databases ; select Host,User,Password from mysql.user'


assert_running "mysql"
assert_iptables_allow "mysql"

assert_docs
