#!/bin/bash

# test: Test debops.checkmk_server
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.apache debops.etc_services debops.ferm git+https://github.com/ganto/ansible-users.git,dependent_vars
# create symlink for correct role naming
ln -s /home/travis/build/ganto/ansible-checkmk_server/rolespec/roles/ansible-users /home/travis/build/ganto/ansible-checkmk_server/rolespec/roles/debops.users

assert_playbook_check_runs
assert_playbook_idempotent


assert_path '/omd/sites/debops'
assert_path '/omd/sites/debops/etc/check_mk/conf.d/wato/global.mk'
assert_path '/omd/sites/debops/etc/check_mk/conf.d/wato/rules.mk'

assert_running 'apache2'
assert_running 'icinga'

assert_url 'http://localhost/debops/' '(200|302)'

assert_docs
