#!/bin/bash

# test: Test debops.saslauthd
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.postfix debops.secret


assert_playbook_check_runs
assert_playbook_idempotent

echo "Contents of /etc/postfix/main.cf"
cat /etc/postfix/main.cf

echo "Contents of /etc/postfix/master.cf"
cat /etc/postfix/master.cf

echo "Contents of /etc/default/saslauthd-smtpd"
cat /etc/default/saslauthd-smtpd

sudo ls -l /var/spool/postfix/var/lib/saslauthd

assert_path "/etc/default/saslauthd-smtpd"
assert_path "/etc/postfix/sasl/smtpd.conf"
assert_running "saslauthd"

# Test documentation
assert_docs

