#!/bin/bash

# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences debops.java

purge openjdk-6-jre openjdk-7-jre default-jre default-jre-headless


assert_playbook_check_runs
assert_playbook_idempotent


apt-cache policy r-base r-recommended

R --version

assert_docs
