#!/bin/bash

# test: Test debops.postconf
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.saslauthd debops.postfix debops.secret debops.ferm


assert_playbook_check_runs
assert_playbook_check_runs
assert_ansible_check_diff
assert_playbook_idempotent

echo "Show firewall configuration"
sudo iptables -v -L

echo "List of files in /etc/postfix"
sudo ls -l /etc/postfix

echo "Contents of /etc/postfix/main.cf"
cat /etc/postfix/main.cf

echo "Contents of /etc/postfix/master.cf"
cat /etc/postfix/master.cf

# Test documentation
assert_docs

