#!/bin/bash

# test: Test debops.postwhite
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.postfix debops.secret debops.postscreen


assert_playbook_check_runs
assert_playbook_idempotent

echo "Contents of /etc/postfix/main.cf"
cat /etc/postfix/main.cf

echo "Contents of /etc/postfix/master.cf"
cat /etc/postfix/master.cf

# Test documentation
assert_docs

