#!/bin/bash

# test: Test debops.owncloud
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy -f install debops.apt_preferences debops.ferm debops.nginx
ansible-galaxy -f install git+https://github.com/ganto/ansible-php.git,pkg-filter
# create symlink for correct role naming
ln -s ansible-php roles/debops.php


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/srv/www/roundcube"

assert_docs
