#!/bin/bash

# test: Test debops.rstudio_server
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.etc_services debops.apt_preferences \
                          debops.nginx debops.java debops.cran


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/usr/lib/rstudio-server"
assert_running "rserver"


# Test documentation
assert_docs
