#!/bin/bash

# test: Test debops.rstudio_server
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


upgrade_packages_xenial python python-dateutil

# Fix python datetime issue
cp -f /usr/bin/python2.7 $(which python2.7)


echo "List contents of /etc/apt/sources.list.d/"
ls -l /etc/apt/sources.list.d


install_ansible ${test_ansible_version}
ansible_plugins

until ansible-galaxy install debops.etc_services debops.apt_preferences debops.nginx debops.java debops.cran debops.ferm ; do
    echo "Waiting 60s..." ; sleep 60 ; echo "Trying installation again..." ; done


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/usr/lib/rstudio-server"
assert_running "rserver"


# Test documentation
assert_docs
