#!/bin/bash

# test: Test debops.etherpad
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


if [ -n "${ROLESPEC_TRAVIS}" ] ; then
  # Fix missing insserv command in Ubuntu Precise
  sudo ln -s /usr/lib/insserv/insserv /usr/sbin/insserv

  # Install nodejs 10.x from saucy
  dist="saucy"
  echo "Upgrade nodejs to >= 10.x for Etherpad"
  echo "deb http://us.archive.ubuntu.com/ubuntu/ ${dist} main restricted universe" | sudo tee /etc/apt/sources.list.d/${dist}.list
  sudo apt-get -qq update
  sudo apt-get -yq install nodejs/${dist} nodejs-legacy/${dist}

  # Disable saucy to not interfere with other packages
  sudo rm -f /etc/apt/sources.list.d/${dist}.list
  sudo apt-get -qq update
fi


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

ansible-galaxy -f install debops.apt_preferences debops.etc_services debops.ferm debops.nginx debops.mariadb debops.mariadb_server debops.nodejs debops.logrotate debops.tcpwrappers


stop mysql
purge ${ROLESPEC_MYSQL_LIBS}
sudo rm -rf /etc/mysql /var/lib/mysql


assert_playbook_check_runs
assert_ansible_check_diff
#assert_playbook_idempotent || printf "%s\n" "The 'npm' module is not idempotent on Ansible 2.3, but shuld work fine on Ansible 2.4"


curl "http://localhost.localdomain/"
assert_url "http://localhost.localdomain"
assert_docs
