#!/bin/bash

# test: Test debops.rails_deploy
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


stop postgresql
purge ${ROLESPEC_POSTGRESQL_LIBS} 
sudo rm -rf /var/lib/postgresql
stop redis-server
stop redis-sentinel
purge redis-server
sudo rm -rf /etc/redis
fix_precise_issues
upgrade_packages nodejs nodejs-legacy


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.pki debops.auth debops.nodejs


# Create a test git config
git config --global user.email 'test@localhost'
git config --global user.name 'Test user'

# Place the test files in a common spot and setup a new git repo 
if [[ -d "/tmp/testapp" ]]; then
  rm -rf /tmp/testapp
fi
cp -r "${ROLESPEC_TEST}/test_files/testapp" "/tmp"
cd "/tmp/testapp"
git init && git add -A && git commit -m "Initial commit"
cd -

if [[ -n "${ROLESPEC_TRAVIS}" ]]; then
  __rvm unload ; rm -rf ~/.rvm
fi


echo "Clean up the environment"
unset rvm_bin_path GEM_HOME IRBRC MY_RUBY_HOME rvm_autoupdate_flag rvm_path RACK_ENV rvm_prefix rvm_version RAILS_ENV GEM_PATH RUBY_VERSION rvm_silence_path_mismatch_check_flag
sudo apt-get --purge -qy remove 'ruby*'

# Add Ruby 2.1 PPA
sudo apt-get -yq install python-software-properties
sudo apt-add-repository -y ppa:brightbox/ruby-ng
sudo apt-get -yq update
apt-cache policy ruby ruby2.1 ruby2.1-dev rubygems-integration

# Fix travis nvm error
chmod 777 -R /home/travis/.nvm


assert_playbook_check_runs
assert_playbook_idempotent


assert_permission "/var/local/testapp" "751"
assert_user_in_group "testapp" "testapp"

assert_in_file "/var/local/testapp/.ssh/id_rsa.pub" "ssh"
assert_in_file "/etc/logrotate.d/testapp" "{"
assert_in_file "/etc/logrotate.d/testapp" "}"

assert_url "https://${ROLESPEC_FQDN}"
assert_url "https://${ROLESPEC_FQDN}/sidekiq"

assert_monitoring "testapp"
assert_monitoring "sidekiq"
