#!/bin/bash

# test: Test debops.etc_aliases
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


echo "Contents of /etc/aliases"
cat /etc/aliases


assert_in_file "/etc/aliases" "root"
assert_in_file "/etc/aliases" "postmaster"


assert_docs

assert_python
