#!/bin/bash

# test: Test debops.opendkim
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


ansible-galaxy install -f debops.postfix debops.secret debops.apt_preferences debops.etc_services debops.unbound


assert_playbook_check_runs
assert_playbook_idempotent

echo "Contents of /etc/postfix/main.cf"
cat /etc/postfix/main.cf

echo "Contents of /etc/postfix/master.cf"
cat /etc/postfix/master.cf

echo "Contents of /etc/opendkim.conf"
cat /etc/opendkim.conf

assert_path "/etc/opendkim.conf"
assert_running "opendkim"

# Test documentation
assert_docs

