#!/bin/bash

# test: Test debops.sftpusers
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


sudo apt-get install tree


assert_playbook_check_runs
assert_playbook_idempotent


echo "Contents of /srv directory"
sudo tree /srv


# Currently there are no docs
#assert_docs
