---

- hosts: 'placeholder_fqdn'
  become: True

  roles:
    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ checkmk_agent__etc_services__dependent_list }}'
      when: (checkmk_agent|d() and 'xinetd' in checkmk_agent)

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ checkmk_agent__ferm__dependent_rules }}'
      when: (checkmk_agent|d() and 'xinetd' in checkmk_agent)

    - role: debops.mariadb
      mariadb__users:
        - '{{ checkmk_agent__mariadb__users }}'
      when: (("mk_mysql" in checkmk_agent__plugin_list and
              checkmk_agent__plugin_mysql|d("automatic") == "automatic") or
             ((checkmk_agent__plugin_autodetect|d(True) | bool) and
              "debops_mariadb_server" in hostvars[inventory_hostname]["group_names"])
            )

    - role: ansible-checkmk_agent
