---

- hosts: 'placeholder_fqdn'
  become: True

  roles:

    - role: ansible-checkmk_agent/env

    - role: debops.apt_preferences
      apt_preferences__dependent_list:
        - '{{ checkmk_agent__apt_preferences__dependent_list }}'

    - role: debops.etc_services
      etc_services__dependent_list:
        - '{{ checkmk_agent__etc_services__dependent_list }}'
      when: ('xinetd' in checkmk_agent__type)

    - role: debops.ferm
      ferm__dependent_rules:
        - '{{ checkmk_agent__ferm__dependent_rules }}'

    - role: debops.tcpwrappers
      tcpwrappers__dependent_allow:
        - '{{ checkmk_agent__tcpwrappers__dependent_allow }}'

    - role: debops.authorized_keys
      authorized_keys__dependent_list:
        - '{{ checkmk_agent__authorized_keys__dependent_list }}'

    - role: debops.mariadb
      mariadb__dependent_users:
        - '{{ checkmk_agent__mariadb__dependent_users }}'
      when: ("mk_mysql" in checkmk_agent__combined_plugins)

    - role: ansible-checkmk_agent
