#!/bin/bash

# test: Test debops.docker
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins

echo "Display Ansible facts"
ansible all -m setup


assert_playbook_check_runs

echo "Debug APT sources"
ls -l /etc/apt/sources.list.d
cat /etc/apt/sources.list.d/*


assert_playbook_idempotent


assert_path "/etc/default/docker"
assert_docs

