#!/bin/bash

# test: Test debops.docker
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


echo "Remove system-wide python-yaml"
sudo apt-get --purge -y remove python-yaml

echo "Install PyYAML from pip"
sudo pip install pyyaml

install_ansible ${test_ansible_version}
ansible_plugins


assert_playbook_check_runs
assert_playbook_idempotent


assert_path "/etc/default/docker"
assert_docs

