#!/bin/bash

# test: Test debops.docker
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


install_ansible ${test_ansible_version}
ansible_plugins


echo "Uninstall existing Docker package"
sudo apt-get --purge -y remove 'docker*'


echo "Remove existing docker APT source"
sudo rm -vf /etc/apt/sources.list.d/docker.list
sudo apt-get -q update


assert_playbook_check_runs
assert_playbook_idempotent

echo "Show docker package policy"
apt-cache policy docker-ce


echo "docker run hello-world"
sudo docker run hello-world


assert_path "/etc/default/docker"
assert_docs
