#!/bin/bash

# test: Test debops.postgresql
# Copyright (C) 2014 Nick Janetakis <nick.janetakis@gmail.com>
# Part of the DebOps project - http://debops.org/


. "${ROLESPEC_LIB}/main"
. "${ROLESPEC_TEST}/../defaults.conf"


#install_ansible ${test_ansible_version}
install_ansible stable-2.2
ansible_plugins


ansible-galaxy install -f debops.postgresql_server


stop postgresql
purge ${ROLESPEC_POSTGRESQL_LIBS}
sudo rm -rf /var/lib/postgresql


assert_playbook_check_runs -vvvv
assert_playbook_idempotent


psql -d travis_test -a -q -X --pset pager=off -c '\l'
psql -d travis_test -a -q -X --pset pager=off -c '\du'


assert_running "postgres"
assert_in_file "/home/travis/.pgpass" "travis"
assert_docs

